#build variable
CC = g++
#option variable
CFLAGS = -o

#object variable
OBJS = mp2_20201588.o 

TARGET = mp2_20201588

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) $(TARGET) $(OBJS)

clean :
	rm -rf $(OBJS) $(TARGET)